### ISSUE TITLE
Enable use for jQuery 2.1.x

### ISSUE THREAD

**Issue by mpemberton5** [components/bootstrap#39]
Could you update to allow for the component jQuery 2.1.x?

Thanks!

**Comment by RobLoach** [comment]
@andrerom? Should it be `~1.9.1 | ~1.10 | ~2.0 | ~2.1`? Seems like we're getting very specific with our version requirements.

**Comment by andrerom** [comment]
Hi,

regarding 6eae8dbb3ed16b3392694f7e39566d8adadd07d2.
`~2.0` should mean anything in 2.x range starting from 0, so unless some other dependency comes into play here I'm not sure what is blocking 2.1 from being usable.

**Comment by RobLoach** [comment]
@mpemberton5 Were you talking for Composer? What package manager are you using? It should allow 2.1.x no problem, as @andrerom covered.

**Comment by mpemberton5** [comment]
Yes, composer was having problems with it.  2.0.x did not appear to include 2.1.x.

**Comment by andrerom** [comment]
Ok, where is `2.0.*` defined?

**Comment by mpemberton5** [comment]
in composer.json

**Comment by mpemberton5** [comment]
"require": {
    "components/jquery": "~1.9.1 | ~1.10 | ~2.0"

**Comment by andrerom** [comment]
Yes, but `~2.0` means "2.x, where x is higher then 0".
ref: https://getcomposer.org/doc/01-basic-usage.md#next-significant-release-tilde-and-caret-operators-

However seems like the requirement should use `||` and not `|` like is the case now (and afaik is format in `conflict`) .

**Comment by mpemberton5** [comment]
I think you are right on the double pipe usage.

Although I understand the specificity of which jquery version, would there be any room for relaxing some of the requirements?

Maybe something like ">=1.9.1 >=1.10 >=2.0"?  Not validated that syntax, but you get the idea.

**Comment by andrerom** [comment]
Looking at the link above we can do `>=1.9.1  <3.0`

**Comment by andrerom** [comment]
Proposed fix in #40

**Comment by martinlindhe** [comment]
thanks for your contribution @andrerom

**Comment by stof** [comment]
@andrerom ``|`` and ``||`` are both valid since a few months.

**Comment by andrerom** [comment]
@stof Ok, any clue to why 2.1 was not matched (as reported above) with `~1.9.1 | ~1.10 | ~2.0` ?

**Comment by stof** [comment]
it should have been matched. This is weird

**Comment by mpemberton5** [comment]
Even the updated match doesn't work:

```
  Problem 1
    - Installation request for components/jquery dev-master -> satisfiable by components/jquery[dev-master].
    - components/bootstrap dev-master requires components/jquery >=1.9.1 <3.0 -> satisfiable by components/jquery[1.10.x-dev, 1.11.x-dev, 1.9.x-dev].
    - Can only install one of: components/jquery[dev-master, 1.10.x-dev].
    - Can only install one of: components/jquery[dev-master, 1.11.x-dev].
    - Can only install one of: components/jquery[dev-master, 1.9.x-dev].
    - Installation request for components/bootstrap dev-master -> satisfiable by components/bootstrap[dev-master].
```

This is my composer.json
```
   "require": {
          "laravel/framework": "5.0.*",
          "components/jquery": "dev-master",
          "components/jqueryui": "dev-master",
          "components/bootstrap": "dev-master"
      },
 ```

**Comment by andrerom** [comment]
Ok, so that explain it. The problem is on your side, you are asking for dev-master.

**Comment by mpemberton5** [comment]
Much appreciated @andrerom and @stof.  Probably isn't best practices to using dev-master anyway.

**Comment by stof** [comment]
it is not indeed
