### ISSUE TITLE
Bootstrap 4.0.0-alpha

### ISSUE THREAD

**Issue by RobLoach** [components/bootstrap#43]
Opened up a 4 branch to update to [Bootstrap 4 Alpha](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/):
https://github.com/components/bootstrap/tree/4

Anyone willing to test it out?

**Comment by avickers** [comment]
Just to drop a note -- I have used this branch in a couple projects using SteveSanderson's [generator-ko](https://github.com/SteveSanderson/generator-ko).  The only real issue is its absence from bower as a prerelease version makes it rather inconvenient for collaborators.

**Comment by Guite** [comment]
Using Bootstrap 4 from the `4` branch works without problems. Closing.
