### ISSUE TITLE
Where is bootstrap 4?

### ISSUE THREAD

**Issue by henno** [components/bootstrap#51]
Its out already.

**Comment by RobLoach** [comment]
Noone has updated it, looks like... Feel free to submit a PR? :+1:

**Comment by X-Coder** [comment]
I just created a [PR](https://github.com/components/bootstrap/pull/52) for 4.1.1, it should work but someone could test it more before merging, because I haven't much time for testing.

**Comment by X-Coder** [comment]
Also I think the sass files should be integrated. See [here](https://github.com/components/bootstrap/pull/41).

**Comment by Guite** [comment]
Just released 4.4.1. Closing.

For the sass files please use https://github.com/martinlindhe/bootstrap-sass instead or in addition.
