### ISSUE TITLE
Consider moving on to Bootstrap v4.2 ?

### ISSUE THREAD

**Issue by bdelespierre** [components/bootstrap#54]
I can do a PR for you if you tell me how to :+1:

**Comment by RobLoach** [comment]
Certainly! There's a branch over at:
https://github.com/components/bootstrap/tree/4

**Comment by indrakaw** [comment]
Latest version on `https://github.com/components/bootstrap/tree/4` within tag is v4.1.1. Please consider add newer to latest versions and keep this repo up-to-dated.

**Comment by Guite** [comment]
Just released 4.4.1. Closing.
